[package]
name = "Crowdfund"
version = "1.0.0"

[addresses]
Crowdfund = "_"

[dev-addresses]
Crowdfund = "0xcf"

[dependencies]
MoveStdlib = { local = "../stdlib", addr_subst = { "Std" = "0x1" } }
DiemExperimental = { local = "../experimental" }
BasicCoin = { local = "../BasicCoin" }
