[package]
name = "Crowdfund"
version = "1.0.0"

[addresses]
Sender = "_"

[dependencies]
MoveStdlib = { local = "../stdlib", addr_subst = { Std = "0x1" } }
DiemExperimental = { local = "../experimental" }
BasicCoin = { local = "../BasicCoin" }
